# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('owner_id', models.IntegerField()),
                ('approved', models.BooleanField(default=True)),
                ('uploadprocessed', models.BooleanField(default=True)),
                ('sha2', models.CharField(max_length=50)),
                ('thumbnail', models.IntegerField()),
                ('errors', models.BooleanField(default=True)),
                ('lastmodified', models.DateField()),
            ],
        ),
    ]
