# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-27 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objects',
            new_name='Object',
        ),
    ]
