# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170327_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='thumbnail',
            field=models.CharField(max_length=50),
        ),
    ]
